<a href="https://colab.research.google.com/github/Manishrdy/ML-DM_Lab/blob/master/Chi_Squared_Test(17409).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [3]:
table = [	[10, 20, 30],
			[6,  9,  17]]

In [4]:
print(table)

[[10, 20, 30], [6, 9, 17]]


In [5]:
stat, p, dof, expected = chi2_contingency(table)

In [14]:
print('Degree of freedom = %d' % dof)

Degree of freedom = 2


In [8]:
print(expected)

[[10.43478261 18.91304348 30.65217391]
 [ 5.56521739 10.08695652 16.34782609]]


In [9]:
# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))

probability=0.950, critical=5.991, stat=0.272


In [10]:
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [11]:
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))

significance=0.050, p=0.873


In [12]:
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


----------Assingment Question----------

In [23]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [24]:
table1 = [	[250, 200],
			[50,  1000]]

In [26]:
print(table1)

[[250, 200], [50, 1000]]


In [31]:
stat1, p1, dof1, expected1 = chi2_contingency(table1)

In [32]:
print('Degree of freedom = %d' % dof1)

Degree of freedom = 1


In [33]:
print(expected1)

[[ 90. 360.]
 [210. 840.]]


In [34]:
alpha1 = 0.05

In [35]:
if p1 <= alpha1:
  print("Dependent")
else:
  print("Independent")

Dependent


In [36]:
alpha2 = 0.001

In [37]:
if p1 <= alpha1:
  print("Dependent")
else:
  print("Independent")

Dependent


----------Practise Problem using random dataset---------


In [39]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [40]:
np.random.seed(10)

In [41]:
voter_race = np.random.choice(a=["asian", "black", "hispanic", "other", "white"],p=[0.05, 0.15 ,0.25, 0.05, 0.5],size = 1000)

In [42]:
voter_party = np.random.choice(a=["democrat", "independent", "republican"],p=[0.4, 0.2, 0.4], size = 1000)

In [43]:
voters = pd.DataFrame({"race":voter_race, "party":voter_party})

In [44]:
voters

race        party
0       white     democrat
1       asian   republican
2       white  independent
3       white   republican
4       other     democrat
..        ...          ...
995     white   republican
996  hispanic  independent
997     black  independent
998     white   republican
999     black     democrat

[1000 rows x 2 columns]

In [50]:
voter_tab = pd.crosstab(voters.race, voters.party, margins=True) 
voter_tab.columns = ["democrat", "independent", "republican", "row_totals"]
voter_tab.index = ["asian", "black", "hispanic", "other", "white", "col_totals"]

In [46]:
voter_tab

democrat  independent  republican  row_totals
race                                                   
asian           21            7          32          60
black           65           25          64         154
hispanic       107           50          94         251
other           15            8          15          38
white          189           96         212         497
All            397          186         417        1000

In [47]:
observed = voter_tab.iloc[0:5, 0:3]
observed

democrat  independent  republican
race                                       
asian           21            7          32
black           65           25          64
hispanic       107           50          94
other           15            8          15
white          189           96         212

In [51]:
expected=np.outer(voter_tab["row_totals"][0:5],voter_tab.loc["col_totals"][0:3])/1000 
expected=pd.DataFrame(expected)
expected.columns = ["democrat", "independent", "republican"]  
expected.index=["asian", "black", "hispanic", "other", "white"]
expected

democrat  independent  republican
asian       23.820       11.160      25.020
black       61.138       28.644      64.218
hispanic    99.647       46.686     104.667
other       15.086        7.068      15.846
white      197.309       92.442     207.249

In [53]:
chi_squared_stat = (((observed-expected) **2)/expected). sum().sum() 
print(chi_squared_stat)

7.169321280162059


In [58]:
crit = stats.chi2.ppf( q=0.95, df = 8)
print("Critical value",crit)
p_value = 1 - stats.chi2.cdf(x=chi_squared_stat, df=8)
print("p value: ",p_value)

Critical value 15.50731305586545
p value:  0.518479392948842


In [59]:
if chi_squared_stat < crit:
    print("""At 0.95 level of significance, we reject the null hypothesis and accept H1.They are not independent.""")
else:
    print ("""At 0.95 level of significance, we accept the null hypothesis.They are independent. """)

At 0.95 level of significance, we reject the null hypothesis and accept H1.They are not independent.


In [60]:
stats = stats.chi2_contingency (observed= observed)
# The returned data includes: chi squared stat, p value, df, expected_crosst
print(stats)

(7.169321280162059, 0.518479392948842, 8, array([[ 23.82 ,  11.16 ,  25.02 ],
       [ 61.138,  28.644,  64.218],
       [ 99.647,  46.686, 104.667],
       [ 15.086,   7.068,  15.846],
       [197.309,  92.442, 207.249]]))
